apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-with-iamidentitymappings
  region: us-east-1

iamIdentityMappings:
  - arn: arn:aws:iam::${ACCOUNT_NUMBER}:role/${CLUSTER_ROLE_ARN}
    groups:
      - system:bootstrapper
#      - system:nodes
    username: system:node:{{EC2PrivateDNSName}}
    noDuplicateARNs: true # prevents shadowing of ARNs

  - arn: arn:aws:iam::${ACCOUNT_NUMBER}:user/myUser@domain.com
    username: myUser
    groups:
      - system:masters
    noDuplicateARNs: true # prevents shadowing of ARNs

  - arn: arn:aws:iam::${ACCOUNT_NUMBER}:user/myUser2@domain.com
    username: myUser2
    groups:
      - system:masters
    noDuplicateARNs: true # prevents shadowing of ARNs

  - account: "${ACCOUNT_NUMBER}" # account must be configured with no other options
