apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-with-iamidentitymappings
  region: us-east-1

iamIdentityMappings:
  - serviceName: emr-containers
    namespace: ${EMR_ON_EKS_NAMESPACE} # serviceName requires namespace

  - account: "${ACCOUNT_NUMBER}" # account must be configured with no other options